### ISSUE TITLE
Changes to model card

### ISSUE THREAD

**Issue by osanseviero** [mv-lab/InstructIR#2]
Hi there! 

I noticed discussions are disabled in the HF repository, so I could not update the model card. I noticed two things:

1. The demo link is broken. It should be 

```
**🚀 You can start with the [demo tutorial](https://github.com/mv-lab/InstructIR/blob/main/demo.ipynb)**
```

2. I suggest adding a pipeline tag to help with discoverability. For example, it could look like

```yaml
---
license: mit
pipeline_tag: image-to-image
---
```
